// ignore_for_file: avoid_print
import 'dart:io';

import 'reverse_runner.dart' show runReverse;

enum _Mode { install, uninstall }

const _macosMarker =
    '<key>com.apple.security.network.client</key>\n\t<true/>';
const _macosLooseMarker = 'com.apple.security.network.client';

const _iosBlock = '''
\t<key>NSAppTransportSecurity</key>
\t<dict>
\t\t<key>NSAllowsLocalNetworking</key>
\t\t<true/>
\t</dict>''';
const _iosLooseMarker = 'NSAllowsLocalNetworking';
const _iosKeyMarker = 'NSAppTransportSecurity';

const _androidMarker = '<!-- owlscope:setup -->';
const _androidAppBlock = '''
    $_androidMarker
    <application
        android:usesCleartextTraffic="true"
        tools:replace="android:usesCleartextTraffic" />
''';
const _androidFreshFile = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Added by owlscope:setup. Run "dart run owlscope:teardown" to remove. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:usesCleartextTraffic="true"
        tools:replace="android:usesCleartextTraffic" />
</manifest>
''';

// ── Release-mode support via Network Security Config ──────────────────
//
// `usesCleartextTraffic="true"` in the debug manifest only applies to debug
// builds. Developers profiling with `flutter run --profile` or
// `--release` need a way to reach `ws://localhost:9090` without weakening
// security for the whole app. Network Security Config solves this: it
// scopes cleartext permission to exact loopback/emulator hosts, leaving
// every other domain HTTPS-only — safe to commit.
//
// The `@xml/owlscope_network_security_config` resource name itself doubles
// as the teardown marker — no separate comment is needed (and XML
// comments cannot appear between attributes inside a tag anyway, so a
// marker comment there would be invalid XML and break the build).
const _nscFileName = 'owlscope_network_security_config.xml';
const _nscFileContent = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by owlscope:setup. Allows cleartext WS only to the OwlScope
     desktop reachable via adb-reverse or the Android emulator host IP.
     Run "dart run owlscope:teardown" to remove. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">10.0.2.2</domain>
        <domain includeSubdomains="false">10.0.3.2</domain>
    </domain-config>
</network-security-config>
''';
const _nscAttribute =
    'android:networkSecurityConfig="@xml/owlscope_network_security_config"';

bool _patchMacEntitlements(String original, _Mode mode, void Function(String) write) {
  final hasIt = original.contains(_macosLooseMarker);
  if (mode == _Mode.install) {
    if (hasIt) return false;
    final idx = original.lastIndexOf('</dict>');
    if (idx == -1) return false;
    final patched = original.replaceRange(
      idx,
      idx,
      '\t$_macosMarker\n',
    );
    write(patched);
    return true;
  } else {
    if (!hasIt) return false;
    final pattern = RegExp(
      r'\s*<key>com\.apple\.security\.network\.client</key>\s*<true\s*/>',
      multiLine: true,
    );
    final patched = original.replaceAll(pattern, '');
    write(patched);
    return true;
  }
}

bool _patchInfoPlist(String original, _Mode mode, void Function(String) write) {
  final hasLoose = original.contains(_iosLooseMarker);
  if (mode == _Mode.install) {
    if (hasLoose) return false;
    if (original.contains(_iosKeyMarker)) {
      // ATS dict already exists — append the localnetworking key inside that dict.
      final pattern = RegExp(
        r'<key>NSAppTransportSecurity</key>\s*<dict>',
      );
      final patched = original.replaceFirstMapped(pattern, (m) {
        return '${m.group(0)}\n\t\t<key>NSAllowsLocalNetworking</key>\n\t\t<true/>';
      });
      if (patched == original) return false;
      write(patched);
      return true;
    }
    // No ATS dict — insert before final </dict>.
    final idx = original.lastIndexOf('</dict>');
    if (idx == -1) return false;
    final patched = original.replaceRange(idx, idx, '$_iosBlock\n');
    write(patched);
    return true;
  } else {
    if (!hasLoose) return false;
    // Remove just our two-line key when it sits in our dedicated block; if ATS dict
    // contains other keys, only strip NSAllowsLocalNetworking, leaving rest intact.
    var patched = original;
    final blockPattern = RegExp(
      r'\n?\s*<key>NSAppTransportSecurity</key>\s*<dict>\s*<key>NSAllowsLocalNetworking</key>\s*<true\s*/>\s*</dict>',
    );
    if (blockPattern.hasMatch(patched)) {
      patched = patched.replaceAll(blockPattern, '');
    } else {
      final innerPattern = RegExp(
        r'\s*<key>NSAllowsLocalNetworking</key>\s*<true\s*/>',
      );
      patched = patched.replaceAll(innerPattern, '');
    }
    if (patched == original) return false;
    write(patched);
    return true;
  }
}

/// Write (or remove) the Network Security Config XML under
/// `android/app/src/main/res/xml/`. Returns true on change. The file is
/// idempotent — re-running install over an existing file is a no-op.
bool _writeAndroidNetworkSecurityConfig(_Mode mode, File f) {
  if (mode == _Mode.install) {
    if (f.existsSync()) return false;
    f.createSync(recursive: true);
    f.writeAsStringSync(_nscFileContent);
    return true;
  } else {
    if (!f.existsSync()) return false;
    final original = f.readAsStringSync();
    // Only delete files we generated, so a hand-written NSC the user
    // might have placed under the same name survives teardown.
    if (!original.contains('Generated by owlscope:setup')) return false;
    f.deleteSync();
    return true;
  }
}

/// Patch `android/app/src/main/AndroidManifest.xml` so the `<application>`
/// tag references our Network Security Config. Without this attribute the
/// XML file is dead weight in profile/release builds.
///
/// Teardown matches the exact attribute string — the resource path
/// `@xml/owlscope_network_security_config` is unique to OwlScope, so a
/// hand-written `android:networkSecurityConfig` set by the developer to
/// some other file won't be touched.
bool _patchMainAndroidManifest(_Mode mode, File f) {
  if (!f.existsSync()) return false;
  final original = f.readAsStringSync();
  if (mode == _Mode.install) {
    if (original.contains(_nscAttribute)) return false; // already patched
    // If the project already declares networkSecurityConfig, don't
    // silently override — surface a warning so the developer can merge.
    if (RegExp(r'android:networkSecurityConfig\s*=').hasMatch(original)) {
      print('  ! android/app/src/main/AndroidManifest.xml already sets '
          'networkSecurityConfig. Merge the entries from '
          'android/app/src/main/res/xml/$_nscFileName manually.');
      return false;
    }
    // Insert our attribute on the <application> opening tag. XML comments
    // cannot appear inside a start tag, so the unique resource path is
    // what teardown will key off — no separate marker needed.
    final appOpen = RegExp(r'<application(\s[^>]*?)?>');
    final m = appOpen.firstMatch(original);
    if (m == null) return false;
    final fullTag = m.group(0)!;
    final inside = m.group(1) ?? '';
    final patchedTag = '<application$inside\n        $_nscAttribute>';
    final patched = original.replaceFirst(fullTag, patchedTag);
    if (patched == original) return false;
    f.writeAsStringSync(patched);
    return true;
  } else {
    if (!original.contains(_nscAttribute)) return false;
    // Strip the attribute and its leading whitespace/newline so the rest
    // of the tag stays formatted as the developer (or Flutter scaffold)
    // had it.
    final pattern = RegExp(r'\n\s*' + RegExp.escape(_nscAttribute));
    final patched = original.replaceAll(pattern, '');
    if (patched == original) return false;
    f.writeAsStringSync(patched);
    return true;
  }
}

bool _writeAndroidDebugManifest(_Mode mode, File f) {
  if (mode == _Mode.install) {
    if (!f.existsSync()) {
      f.createSync(recursive: true);
      f.writeAsStringSync(_androidFreshFile);
      return true;
    }
    final original = f.readAsStringSync();
    if (original.contains(_androidMarker)) return false; // already done

    var patched = original;
    if (!patched.contains('xmlns:tools=')) {
      patched = patched.replaceFirstMapped(
        RegExp(r'<manifest([^>]*)>'),
        (m) =>
            '<manifest${m.group(1)} xmlns:tools="http://schemas.android.com/tools">',
      );
    }
    patched = patched.replaceFirst('</manifest>', '$_androidAppBlock</manifest>');
    f.writeAsStringSync(patched);
    return true;
  } else {
    if (!f.existsSync()) return false;
    final original = f.readAsStringSync();

    if (original.contains('Added by owlscope:setup')) {
      // We created the entire file ourselves — safe to delete.
      f.deleteSync();
      return true;
    }
    if (original.contains(_androidMarker)) {
      final pattern = RegExp(
        r'\s*<!-- owlscope:setup -->\s*<application[^/]*android:usesCleartextTraffic[^/]*/>',
      );
      final patched = original.replaceAll(pattern, '');
      if (patched == original) return false;
      f.writeAsStringSync(patched);
      return true;
    }
    return false;
  }
}

void _runSetup(_Mode mode) {
  final cwd = Directory.current.path;
  final pubspec = File('$cwd/pubspec.yaml');
  if (!pubspec.existsSync()) {
    print('owlscope: no pubspec.yaml in current directory ($cwd)');
    exitCode = 1;
    return;
  }

  final modeLabel = mode == _Mode.install ? 'setup' : 'teardown';
  print('OwlScope $modeLabel — project: $cwd\n');

  final results = <String>[];

  // macOS
  final macFile = File('$cwd/macos/Runner/DebugProfile.entitlements');
  if (macFile.existsSync()) {
    final original = macFile.readAsStringSync();
    final changed = _patchMacEntitlements(original, mode, macFile.writeAsStringSync);
    results.add(changed
        ? '  ✓ macOS entitlements ${mode == _Mode.install ? "patched" : "reverted"}'
        : '  · macOS entitlements already ${mode == _Mode.install ? "set" : "clean"}');
  } else {
    results.add('  · macOS: no DebugProfile.entitlements (skipped)');
  }

  // iOS
  final iosFile = File('$cwd/ios/Runner/Info.plist');
  if (iosFile.existsSync()) {
    final original = iosFile.readAsStringSync();
    final changed = _patchInfoPlist(original, mode, iosFile.writeAsStringSync);
    results.add(changed
        ? '  ✓ iOS Info.plist ${mode == _Mode.install ? "patched" : "reverted"}'
        : '  · iOS Info.plist already ${mode == _Mode.install ? "set" : "clean"}');
  } else {
    results.add('  · iOS: no Runner/Info.plist (skipped)');
  }

  // Android — three independent steps:
  //   1. Debug manifest with `usesCleartextTraffic` (only `flutter run`).
  //   2. Network Security Config + main-manifest reference. This is the
  //      part that makes `flutter run --profile` / `--release` reach
  //      `ws://localhost:9090` while keeping every other domain
  //      HTTPS-only. Without it, release builds silently fail to connect.
  final androidDir = Directory('$cwd/android/app');
  if (androidDir.existsSync()) {
    final f = File('$cwd/android/app/src/debug/AndroidManifest.xml');
    final changed = _writeAndroidDebugManifest(mode, f);
    results.add(changed
        ? '  ✓ Android debug manifest ${mode == _Mode.install ? "created" : "removed"}'
        : '  · Android debug manifest already ${mode == _Mode.install ? "present" : "absent or user-owned"}');

    final nscFile =
        File('$cwd/android/app/src/main/res/xml/$_nscFileName');
    final nscChanged = _writeAndroidNetworkSecurityConfig(mode, nscFile);
    results.add(nscChanged
        ? '  ✓ Android network security config ${mode == _Mode.install ? "written" : "removed"} '
            '(release/profile builds can reach localhost)'
        : '  · Android network security config already ${mode == _Mode.install ? "present" : "absent or user-owned"}');

    final mainManifest =
        File('$cwd/android/app/src/main/AndroidManifest.xml');
    final mainChanged = _patchMainAndroidManifest(mode, mainManifest);
    results.add(mainChanged
        ? '  ✓ Android main manifest ${mode == _Mode.install ? "patched to reference NSC" : "reverted"}'
        : '  · Android main manifest already ${mode == _Mode.install ? "patched" : "clean"}');
  } else {
    results.add('  · Android: no android/app directory (skipped)');
  }

  for (final r in results) {
    print(r);
  }

  // For install, also `adb reverse` so a USB-attached Android phone can
  // reach the desktop via `localhost:9090` immediately. No-op if no
  // device is plugged in or `adb` is missing — matches the RN setup CLI
  // so developers don't have to remember a second command.
  if (mode == _Mode.install) {
    print('');
    runReverse();
  }

  print('');
  if (mode == _Mode.install) {
    print('Done. You can now run: flutter run');
    print('');
    print('Profiling release performance? Pass enableInRelease: true and run');
    print('  flutter run --profile   (recommended — strips assertions, keeps observatory)');
    print('  flutter run --release   (AOT — closest to what users see)');
    print('');
    print('To revert later: dart run owlscope:teardown');
  } else {
    print('Reverted. Remove the import from your code and pubspec to fully detach:');
    print('  flutter pub remove owlscope');
  }
}

void runInstall() => _runSetup(_Mode.install);
void runUninstall() => _runSetup(_Mode.uninstall);
